#!/bin/bash
PRJNAME=${PWD##*/} 
rm -rf $PRJNAME.xcodeproj
swift package generate-xcodeproj
if [[ -n $(find ./Sources -name main.swift) ]]
then
SCHPATH=$PRJNAME.xcodeproj/xcuserdata/$USER.xcuserdatad/xcschemes
mkdir -p $SCHPATH
cat > $SCHPATH/$PRJNAME.xcscheme <<-EOM
<?xml version="1.0" encoding="UTF-8"?>
<Scheme
   LastUpgradeVersion = "0900"
   version = "1.3">
   <BuildAction
      parallelizeBuildables = "YES"
      buildImplicitDependencies = "YES">
      <BuildActionEntries>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "YES"
            buildForArchiving = "YES"
            buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "$PRJNAME::$PRJNAME"
               BuildableName = "$PRJNAME"
               BlueprintName = "$PRJNAME"
               ReferencedContainer = "container:$PRJNAME.xcodeproj">
            </BuildableReference>
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <TestAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      language = ""
      shouldUseLaunchSchemeArgsEnv = "YES">
      <Testables>
      </Testables>
      <MacroExpansion>
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "$PRJNAME::$PRJNAME"
            BuildableName = "$PRJNAME"
            BlueprintName = "$PRJNAME"
            ReferencedContainer = "container:$PRJNAME.xcodeproj">
         </BuildableReference>
      </MacroExpansion>
      <AdditionalOptions>
      </AdditionalOptions>
   </TestAction>
   <LaunchAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      language = ""
      launchStyle = "0"
      useCustomWorkingDirectory = "YES"
      customWorkingDirectory = "\$PROJECT_DIR"
      ignoresPersistentStateOnLaunch = "NO"
      debugDocumentVersioning = "YES"
      debugServiceExtension = "internal"
      allowLocationSimulation = "YES">
      <BuildableProductRunnable
         runnableDebuggingMode = "0">
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "$PRJNAME::$PRJNAME"
            BuildableName = "$PRJNAME"
            BlueprintName = "$PRJNAME"
            ReferencedContainer = "container:$PRJNAME.xcodeproj">
         </BuildableReference>
      </BuildableProductRunnable>
      <EnvironmentVariables>
EOM
for keyvalue in $*; do 
  echo $keyvalue | awk -F'[=]' '{print "\t<EnvironmentVariable \n\t\t key = \"" $1 "\"\n\t\tvalue = \"" $2 "\"\n\t\tisEnabled = \"YES\">\n\t</EnvironmentVariable>"}' >> $SCHPATH/$PRJNAME.xcscheme; 
done
 
cat >> $SCHPATH/$PRJNAME.xcscheme <<-EOM
      </EnvironmentVariables>
      <AdditionalOptions>
      </AdditionalOptions>
   </LaunchAction>
   <ProfileAction
      buildConfiguration = "Release"
      shouldUseLaunchSchemeArgsEnv = "YES"
      savedToolIdentifier = ""
      useCustomWorkingDirectory = "NO"
      debugDocumentVersioning = "YES">
      <BuildableProductRunnable
         runnableDebuggingMode = "0">
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "$PRJNAME::$PRJNAME"
            BuildableName = "$PRJNAME"
            BlueprintName = "$PRJNAME"
            ReferencedContainer = "container:$PRJNAME.xcodeproj">
         </BuildableReference>
      </BuildableProductRunnable>
   </ProfileAction>
   <AnalyzeAction
      buildConfiguration = "Debug">
   </AnalyzeAction>
   <ArchiveAction
      buildConfiguration = "Release"
      revealArchiveInOrganizer = "YES">
   </ArchiveAction>
</Scheme>
EOM
else
SCHPATH=$PRJNAME.xcodeproj/xcshareddata/xcschemes
cat > $SCHPATH/$PRJNAME-Package.xcscheme <<-EOM
<?xml version="1.0" encoding="UTF-8"?>
<Scheme
   LastUpgradeVersion = "9999"
   version = "1.3">
   <BuildAction
      parallelizeBuildables = "YES"
      buildImplicitDependencies = "YES">
      <BuildActionEntries>
         <BuildActionEntry
            buildForTesting = "YES"
            buildForRunning = "YES"
            buildForProfiling = "YES"
            buildForArchiving = "YES"
            buildForAnalyzing = "YES">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "swtt::swtt"
               BuildableName = "swtt.framework"
               BlueprintName = "swtt"
               ReferencedContainer = "container:swtt.xcodeproj">
            </BuildableReference>
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <TestAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      language = ""
      shouldUseLaunchSchemeArgsEnv = "YES">
      <Testables>
         <TestableReference
            skipped = "NO">
            <BuildableReference
               BuildableIdentifier = "primary"
               BlueprintIdentifier = "swtt::swttTests"
               BuildableName = "swttTests.xctest"
               BlueprintName = "swttTests"
               ReferencedContainer = "container:swtt.xcodeproj">
            </BuildableReference>
         </TestableReference>
      </Testables>
      <AdditionalOptions>
      </AdditionalOptions>
   </TestAction>
   <LaunchAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      language = ""
      launchStyle = "0"
      useCustomWorkingDirectory = "YES"
      customWorkingDirectory = "\$PROJECT_DIR"
      ignoresPersistentStateOnLaunch = "NO"
      debugDocumentVersioning = "YES"
      debugServiceExtension = "internal"
      allowLocationSimulation = "YES">
      <MacroExpansion>
         <BuildableReference
            BuildableIdentifier = "primary"
            BlueprintIdentifier = "swtt::swtt"
            BuildableName = "swtt.framework"
            BlueprintName = "swtt"
            ReferencedContainer = "container:swtt.xcodeproj">
         </BuildableReference>
      </MacroExpansion>
      <EnvironmentVariables>
EOM
for keyvalue in $*; do 
  echo $keyvalue | awk -F'[=]' '{print "\t<EnvironmentVariable \n\t\t key = \"" $1 "\"\n\t\tvalue = \"" $2 "\"\n\t\tisEnabled = \"YES\">\n\t</EnvironmentVariable>"}' >> $SCHPATH/$PRJNAME-Package.xcscheme; 
done
 
cat >> $SCHPATH/$PRJNAME-Package.xcscheme <<-EOM
      </EnvironmentVariables>
      <AdditionalOptions>
      </AdditionalOptions>
   </LaunchAction>
   <ProfileAction
      buildConfiguration = "Release"
      shouldUseLaunchSchemeArgsEnv = "YES"
      savedToolIdentifier = ""
      useCustomWorkingDirectory = "NO"
      debugDocumentVersioning = "YES">
   </ProfileAction>
   <AnalyzeAction
      buildConfiguration = "Debug">
   </AnalyzeAction>
   <ArchiveAction
      buildConfiguration = "Release"
      revealArchiveInOrganizer = "YES">
   </ArchiveAction>
</Scheme>
EOM
fi